backend:
  name: github
  repo: JacobKant/blog

media_library:
  name: uploadcare
  config:
    publicKey: 3cbb44108359e835c387

public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Ссылка, widget: string }
      - { name: date, label: Дата, widget: date }
      - { name: titleImage, label: Главная картинка, widget: image}
      - { name: title, label: Заголовок, widget: string }
      - { name: body, label: Тело статьи, widget: markdown }